### ISSUE TITLE
Every attribute has a label

### ISSUE THREAD

**Issue by Moe633** [spectacles-ci/lkmlstyle#9]
Hey Spectacles,

Is it possible to add a rule similar to every dimension and measure having a description, but for labels. We wanted to make sure that every dimension and every measure we have has a label.

Our structure has gone through changes and we find it crucial to ensure that the labels help navigate our explores with proper labels. Just want to make sure that no label is missed.

**Comment by joshtemple** [comment]
Hey @Moe633! With the latest version of lkmlstyle, 0.0.8, you can add your own custom rules to a config file (`lkmlstyle.yaml`). I recommend copying the existing rule for descriptions and modifying it to check for the `label` field on dimensions, dimension groups, and measures instead.

Check out the updated README for a quick tutorial and let me know if you get stuck.

As a tip, you'll need to...

1. Create a config file in your project repo (you can copy the example file in the root of this repo)
1. Copy the YAML rule definition for the descriptions rule
1. Modify the rule so it checks for labels instead of descriptions
1. Update the `select` field on the custom rule to check for dimensions, dimension groups, and measures
